src/Entity/Booking.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention ceci doit être une date au format jj/mm/aaaa !")
     * @Assert\GreaterThan("today", message="La date d'arrivée ne peut être ultérieur à aujourd'hui")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     *
     * @Assert\Date(message="Attention ceci doit être une date au format jj/mm/aaaa !")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ ne peut être avant/ou le même jour que votre arrivée !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $message;

    /**
     * Set the createdAt to today and the amount is calculated with the diff between startDate and endDate
     *
     * @ORM\PrePersist()
     */
    public function prePersist(){
        if(empty($this->createdAt)){
            $this->createdAt = new \DateTime();
        }
        if(empty($this->amount)){
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    /**
     * Permet de connaitre le temps du séjour en faisant une diff entre startDate et endDate
     *
     * @return integer
     */
    public function getDuration(){
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }


    /**
     * Permet d'obtenir un tableau des jours déjà loué
     *
     * @return array Un array Datetime qui represente les jours déja loué
     */
    public function getNotAvailableDays(){
        $notAvailableDays = [];

        //Pour rappel un timestamp est le tps écoulé depuis le 1er janvier 1970 00:00:00 GMT jusqu'à la date choisi mesurée en secondes

        foreach($this->bookings as $booking){ //je prends chaque date booked
            // je calcule le timestamp entre la startDate et la endDate
            $result = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60 // caclcul du nbre de jour en timestamp entre les deux
            );

            // permet de transformer un tableau en un tableau transformé, ici on passe de timestamp en datetime
            $days = array_map(
                function ($dayTimestamp){
                    return new DateTime(date('Y-m-d', $dayTimestamp));
                }, $result);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
    }


    /**
     * Permet de savoir quelles sont les dates dispo
     *
     * @return mixed
     */
    public function isBookableDates(){
        // On récupère les dates non dispo
        $notAvailableDays   = $this->ad->getNotAvailableDays();

        // Comparaison entre les dates choisies et les dates prises
        $bookingDays        = $this->getDays();

        // Je transforme mes 2 tableaux qui sont des datetime en string car plus facile a comparer
        $days = array_map(function($day){
           return $day->format('Y-m-d');
        }, $bookingDays);

        $notAvailable = array_map(function ($day){
            return $day->format('Y-m-d');
        },$notAvailableDays);

        //on peut refacto le code du dessus
//        $formatDay = function($day){
//            return $day->format('Y-m-d');
//        };

//        $bookedDays     = array_map($formatDay, $bookingDays);
//
//        $notAvailable   = array_map($formatDay, $notAvailableDays);

        // Je cherche dans mon tableau notAvailable si je trouve une de mes valeurs de mon tableau bookedDays
        foreach ($days as $day){
            if(array_search($day, $notAvailable) !== false) return false;

        }

        return true;
    }


    /**
     * Permet de connaitre quelles sont les jours choisis par l'utilisateur
     *
     * @return array
     */
    public function getDays(){
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function ($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
                }, $resultat );

        return $days;

    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @param mixed $message
     */
    public function setMessage($message): void
    {
        $this->message = $message;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *      fields={"email"},
 *     message= "Cet email est déjà utilisé"
 * )
 *
 * @UniqueEntity(
 *     fields={"pseudo"},
 *     message= "Ce pseudo est déjà utilisé"
 * )
 *
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @Assert\Type(type="string")
     * @Assert\Length(
     *      min = 2,
     *      max = 30,
     *      minMessage = "Vous devez écrire un texte d'au moins {{ limit }} caractères",
     *      maxMessage = "Vous devez écrire un texte de {{ limit }} caractères maximum"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @Assert\NotBlank()
     * @Assert\Type(type="string")
     * @Assert\Length(
     *      min = 2,
     *      max = 100,
     *      minMessage = "Vous devez écrire un texte d'au moins {{ limit }} caractères",
     *      maxMessage = "Vous devez écrire un texte de {{ limit }} caractères maximum"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @Assert\NotBlank()
     * @Assert\Email(message = "Ceci n'est pas une url valide")
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 5,
     *      max = 200,
     *      minMessage = "Vous devez écrire un texte d'au moins {{ limit }} caractères",
     *      maxMessage = "Vous devez écrire un texte de {{ limit }} caractères maximum"
     * )
     * @Assert\Type(type="string")
     * @ORM\Column(type="string", length=255)
     */
    private $introduction;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 50,
     *      max = 2000,
     *      minMessage = "Vous devez écrire un texte d'au moins {{ limit }} caractères",
     *      maxMessage = "Vous devez écrire un texte de {{ limit }} caractères maximum"
     * )
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\Length(min=8, minMessage="Votre mot de passe doit faire {{ limit }} caractères minimum")
     */
    private $passwordHash;

    /**
     * @Assert\EqualTo(propertyPath="passwordHash", message="Les mots de passe ne sont pas identiques...")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @Assert\NotBlank()
     * @Assert\Type(type="string")
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Vous devez écrire un texte d'au moins {{ limit }} caractères",
     *      maxMessage = "Vous devez écrire un texte de {{ limit }} caractères maximum"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
    }

    /**
     * Sert a initialiser un slug a chaque création d'annonce
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug(){
        $slugify = new Slugify();
        $this->slug = $slugify->slugify($this->firstName . " " .$this->lastName);
    }

    public function getFullName(){
        return $this->getFirstName() . " " . $this->getLastName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPasswordHash(): ?string
    {
        return $this->passwordHash;
    }

    public function setPasswordHash(string $passwordHash): self
    {
        $this->passwordHash = $passwordHash;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     */
    public function getRoles()
    {
        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();})->toArray();

            $roles[] = 'ROLE_USER';

       return $roles;
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     */
    public function getPassword()
    {
        return $this->passwordHash;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     */
    public function getSalt() {}

    /**
     * Returns the username used to authenticate the user.
     *
     */
    public function getUsername()
    {
       return ($this->email);
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials(){}

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce : {{ ad.title }} !{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous" />
{% endblock %}

{% block body %}
    <div class="container">

        <h1 class="alert alert-info mt-5">Vous êtes sur le point de réserver le bien de <strong>{{ ad.author.fullName }}</strong></h1>

        <h2 class="alert-heading display-3 mt-5 text-center"><strong><em>Votre futur hébergement de rêve !</em></strong></h2>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ ad.title }}</h5>
                <p class="card-text">{{ ad.introduction }}</p>
            </div>
            <img class="card-img-bottom" src="{{ ad.coverImage }}" alt="{{ ad.title }}">
            <div class="card-footer text-muted">
                {{ ad.contents | raw }}
            </div>
        </div>
        {{ form_start(form) }}
        <div class="alert alert-secondary mt-4">
            <h2 class="display-4">Quelles dates souhaitez-vous réserver ?</h2>
            <div class="row mt-3">
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col">
                    {{ form_row(form.endDate) }}
                </div>
            </div>

            {{ form_row(form.message) }}

            <h3 class="mt-3"><em>Le prix de la location par nuit est de </em><strong id="price">{{ ad.price }}</strong> &euro;</h3>
            <h3 class="mt-3"><em>Vous souhaitez louer </em><strong id="days">0</strong> jours</h3>
            <div class="row my-3">
                <h1 class="ml-3"><u>Montant total du séjour :</u><span id="amount"><strong><em> 0</em> </strong></span> &euro;</h1>
            </div>
            <button class="btn btn-success">Je réserve !</button>
        </div>
        {{ form_end(form) }}
    </div>

{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha256-bqVeqGdJ7h/lYPq6xrPv/YGzMEb6dNxlfiTUHSgRCp8=" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function(){
            const dates = $('#booking_startDate, #booking_endDate');

            dates.datepicker(
                {
                format: 'dd/mm/yyyy',
                datesDisabled: [
                    {% for day in ad.notAvailableDays %}
                    "{{ day.format('d/m/Y') }}",
                    {% endfor %}
                ],
                startDate: new Date()
            });

            dates.on('change', totalAmount);
        });

        function totalAmount(){

            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));

            if (startDate && endDate && startDate < endDate) {

                const DAY_TIME = 24 * 60 * 60 * 1000;
                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DAY_TIME;

                const amount = {{ ad.price }} * days;

                $('#days').text(days);
                $('#amount').text(amount);
            }
        }


    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% set ad = booking.ad %}
    {% set author = ad.author %}

    <div class="container alert alert-info">

        {% if app.request.query.get('success') %}
            <div class="alert alert-success text-center ">
                <h4 class="alert-heading display-4">
                    Bravo !
                </h4>
                <p>
                    Votre réservation auprès de <strong><a href="{{ path('user_profile', {'slug' : author.slug}) }}">{{ ad.author.fullName }}</a></strong> pour l'annonce
                    <strong><a href="{{ path('ads_show', {'slug' : ad.slug}) }}">{{ ad.title }}</a></strong>
                </p>
            </div>
        {% endif %}

        <h1 class="display-2"><strong>Réservation n° {{ booking.id }}</strong></h1>

        <div class="row ">
            <div class="col">
                <div class="alert alert-primary">
                    <h2><strong>Détails</strong></h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{ booking.id }}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{ booking.duration }}</dd>
                        <dt class="col-md-4">Montant Total</dt>
                        <dd class="col-md-8">{{ booking.amount }} &euro;</dd>
                        {% if booking.message is not empty %}
                           <dt class="col-md-4">Message</dt>
                           <dd class="col-md-8">{{ booking.message }}</dd>
                        {% endif %}
                    </dl>
                    <hr>

                    <h2 class="alert-heading display-3 text-center"><strong>Votre hôte</strong></h2>
                    <div class="row ">
                        <div class="col-3">
                            <img class="avatar-resa" src="{{ author.picture }}" alt="avatar de {{ author.fullName }}e">
                            <span class="badge badge-primary ml-3 mt-2"> {{  author.ads | length }}{% if author.ads | length >= 2 %}  annonces {% else %} annonce {% endif %}</span>
                        </div>
                        <div class="col ml-3 text-center">
                            <h4>
                                <a href="{{ path('user_profile', {'slug': author.slug}) }}"> Profil de {{ author.fullName }}</a>
                            </h4>
                            <h2 class="mt-3">{{ author.introduction | raw }}</h2>
                        </div>
                    </div>
                    <blockquote class="blockquote mt-4">{{ author.description | raw }}</blockquote>
                    <a href="{{ path('user_profile', {'slug': author.slug}) }}" class="btn btn-info">Plus d'info sur {{ author.firstName }}</a>

                </div>
             </div>
            <div class="col mb-5">
                <div class="alert alert-secondary ">
                    <h2 class="alert-heading h1 mb-4 text-center"><strong>Votre futur hébergement</strong></h2>
                    <h4 class="text-center">
                        <a  style="text-decoration: none" href="{{ path('ads_show', {'slug' : ad.slug}) }}">{{ ad.title }}
                    </h4>
                    <img src="{{ ad.coverImage }}" alt="{{ ad.title }}" class=" mb-3 img-fluid">
                    </a>
                    {{ ad.contents | raw }}
                    <a href="{{ path('ads_show', {'slug' : ad.slug}) }}" class="btn btn-primary">Plus d'informations</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}